-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Máy chủ: 127.0.0.1
-- Thời gian đã tạo: Th10 31, 2022 lúc 10:54 AM
-- Phiên bản máy phục vụ: 10.4.25-MariaDB
-- Phiên bản PHP: 8.1.10

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Cơ sở dữ liệu: `gear`
--

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `product`
--

CREATE TABLE `product` (
  `id_sp` int(11) NOT NULL,
  `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `category` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `soluong` int(11) NOT NULL,
  `tinhtrang` varchar(20) COLLATE utf8_unicode_ci NOT NULL,
  `mota` longtext COLLATE utf8_unicode_ci NOT NULL,
  `gia` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `hinh` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `soluongban` int(11) NOT NULL,
  `thuonghieu` int(11) NOT NULL,
  `subcate` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Đang đổ dữ liệu cho bảng `product`
--

INSERT INTO `product` (`id_sp`, `name`, `category`, `soluong`, `tinhtrang`, `mota`, `gia`, `hinh`, `soluongban`, `thuonghieu`, `subcate`) VALUES
(1, 'Chuột Logitech G502 X Plus LightSpeed White', 'Chuột', 15, 'Mới', 'Đánh giá chi tiết chuột Logitech G502 X Plus LightSpeed White\r\nChuột Logitech G502 X PLUS White là sản phẩm mới nhất của series G502 đình đám. Được thiết kế lại và cải tiến với công nghệ chơi game hiện đại, bao gồm công tắc Lightforce lai quang học - cơ học đầu tiên, Lightspeed không dây, LIGHT SYNC RGB và cảm biến quang học Hero 25K, Logitech G502 X PLUS chắc chắn là một trong những gaming gear đáng mua nhất cho game thủ thời gian sắp tới.\r\n\r\nSwitch LightForce lai quang học - cơ học\r\nCác phím switch quang học lai cơ học đột phá, đạt được cấp độ mới về tốc độ và độ tin cậy thông qua kích hoạt quang học. Song song đó, kích hoạt cơ học giữ lại phản hồi rõ ràng, trực quan mà người chơi yêu thích. \r\n\r\nHỗ trợ đèn RGB Light Sync\r\nCông nghệ RGB Light Sync cho phép chiếu sáng toàn phổ động với khả năng kiểm soát hoàn toàn khoảng 16,8 triệu màu sống động trong dãy 8 đèn LED. Tính năng phát hiện chơi chủ động sẽ tự động tắt đèn khi bạn dùng tay che nó, giúp tiết kiệm pin. Người dùng có thể tùy chỉnh mọi thứ trên phần mềm trực quan G HUB, bao gồm cá nhân hóa nâng cao và các hiệu ứng phương tiện khác.', '3590000', 'logitech_502.jpg', 7, 1, 2),
(2, 'Chuột Logitech G102 Lightsync RGB Black', 'Chuột', 11, 'Mới', 'Đánh giá chi tiết chuột Logitech G102 Lightsync RGB Black\r\nDù có mức giá rất bình dân nhưng chuột Logitech G102 Lightsync RGB lại được trang bị led  RGB 16,8 triệu màu .Chọn một màu hay trộn 3 màu, hiệu ứng có sẵn hay tạo hiệu ứng của riêng bạn . Sự lựa chọn là của bạn ! Bạn còn có thể đồng bộ chuột với thiết bị LIGHTSYNC của Logitech G khác giúp góc máy trở nên đồng bộ và độc đáo hơn.\r\n\r\nCảm biến cấp độ chơi game\r\nTheo dõi con trỏ chính xác và đạt hiệu suất phản hồi nhanh nhạy nhờ vào cảm biến cấp độ chơi game. Với độ nhạy có thể tùy chỉnh từ 200 - 8.000 DPI cùng feet chuột chất lượng, hãy chọn mức độ phù hợp với sở thích chơi của bạn. Sử dụng phần mềm HUB G của Logitech để lập trình lên tới 5 chế độ thiết lập sẵn.\r\n\r\nĐáng tin cậy và có thiết kế phù hợp\r\nMột trong những dòng chuột máy tính sở hữu thiết kế sáu nút cổ điển đem đến cả sự thoải mái lẫn tự tin để bạn có thể khám phá, sáng tạo và chơi như ý muốn. Sử dụng phần mềm HUB G của Logitech để gán các lệnh trong trò chơi, điều khiển hệ thống hoặc tổ hợp phím và đơn giản hóa việc chơi game của bạn.', '559000', 'logitech_102.jpg', 22, 1, 2),
(3, 'Chuột Logitech G Pro X Superlight Wireless Black', 'Chuột', 9, 'Mới', 'Đánh giá chi tiết chuột Logitech G Pro X Superlight Wireless Black:\r\n\r\nĐột phá về thiết kế và trọng lượng\r\nChuột Logitech G Pro X Superlight Wireless Black là một trong những dòng chuột máy tính nhẹ nhất từ trước tới nay của Logitech, Logitech G Pro X Superlight Wireless White là bước đột phá về kỹ thuật khi đạt được trọng lượng ít hơn 63 gram – nhẹ hơn gần 25% so với chuột PRO không dây tiêu chuẩn của Logitech.\r\n\r\nCảm biến HERO 25K độc quyền từ Logitech\r\nChuột Logitech G Pro X Superlight Wireless Black sở hữu mắt cảm biến HERO 25K độc quyền của Logitech G đem lại độ chính xác, tốc độ và độ ổn định. Với độ chính xác cao và khả năng điều khiển cực tốt điều đó sẽ hỗ trợ và mang đến cho người dùng hoàn toàn tự tin, đặc biệt là trong những thời khắc căng thẳng, kéo dài từng giây của trận đấu.\r\n\r\nMột trong những dòng chuột máy tính không dây đáng sở hữu nhất hiện nay, có chân lớn bằng nhựa tổng hợp PTFE không pha tạp mang lại cảm giác lướt êm ái, đem đến kết nối tinh thuần, mượt mà với trò chơi.', '3450000', 'logitrech_pro.jpg', 4, 1, 1),
(7, 'Màn hình ASUS ProArt PA278QV 27\" IPS 2K 60Hz ', 'Màn hình', 7, 'Mới', 'Đánh giá chi tiết màn hình ASUS ProArt PA278QV 27\" IPS 2K 75Hz chuyên đồ họa\r\nMàu sắc vượt trội, sáng tạo không giới hạn\r\nMàn hình ASUS ProArt PA278QV 27\" IPS 2K 75Hz  chuyên đồ họa là màn hình 27-inch được thiết kế để đáp ứng nhu cầu của các chuyên gia sáng tạo nội dung, từ chỉnh sửa ảnh và video đến thiết kế đồ họa. Màn hình ASUS ProArt PA278QV được cân màu tại nhà máy với chứng nhận Calman Verified để mang lại độ chính xác màu tuyệt vời (∆E <2). Cung cấp 100% sRGB / 100% Rec theo tiêu chuẩn công nghiệp. Độ bao phủ không gian màu 709. Cổng USB-C tích hợp hỗ trợ truyền dữ liệu, xuất hình DisplayPort và cũng là đầu cấp nguồn 65W tất cả chỉ thông qua một dây cáp mang đến giải pháp tiện lợi và gọn gàng cho khu vực bàn làm việc của bạn. Màn hình ASUS ProArt PA278QV 27 giúp bạn dễ dàng hoàn thành tác phẩm theo ý muốn một cách nhanh chóng, dễ dàng và chính xác.\r\nMang lại vẻ đẹp thực sự cho hình ảnh của bạn\r\nMàn hình ASUS ProArt PA278QV cung cấp 100% sRGB / 100% Rec theo tiêu chuẩn công nghiệp. 709 và hỗ trợ gam màu DCI-P3 giúp tái tạo sống động, phong phú đảm bảo mọi chi tiết trong ảnh của bạn đều rõ ràng và sinh động như thật.\r\nĐộ trung thực màu cao cho các sắc độ màu thực sự biểu cảm\r\nSay mê ngắm nhìn các sắc độ thuần khiết, biểu cảm nhờ khả năng tại tạo màu chính xác, trung thực. Màn hình ASUS ProArt PA278QV đạt được ∆E < 2 để tái tạo chính xác hình ảnh của bạn trên màn hình, cho phép bạn có được hình dung chính xác về tác phẩm khi hoàn thành.', '9550000', 'asus_pro27.png', 3, 6, 10),
(8, 'Màn hình ASUS ProArt PA247CV 24\" IPS 60Hz USBC ', 'Màn hình', 8, 'Mới', 'Đánh giá chi tiết màn hình Đồ Họa Asus ProArt PA247CV\r\nMàu sắc vượt trội, sáng tạo không giới hạn\r\nMang lại vẻ đẹp thực sự cho hình ảnh của bạn\r\nMàn hình ProArt cung cấp 100% sRGB / 100% Rec theo tiêu chuẩn công nghiệp. 709 và hỗ trợ gam màu DCI-P3 giúp tái tạo sống động, phong phú đảm bảo mọi chi tiết trong ảnh của bạn đều rõ ràng và sinh động như thật.\r\n\r\nĐộ trung thực màu cao cho các sắc độ màu thực sự biểu cảm\r\nSay mê ngắm nhìn các sắc độ thuần khiết, biểu cảm nhờ khả năng tại tạo màu chính xác, trung thực. Màn hình Asus đồ hoạ ProArt đạt được ∆E < 2 để tái tạo chính xác hình ảnh của bạn trên màn hình, cho phép bạn có được hình dung chính xác về tác phẩm khi hoàn thành.\r\n\r\nMàu sắc chân thực, không cần điều chỉnh ban đầu\r\nCác chuyên gia về màu sắc trông cậy vào các màn hình có độ chính xác màu cao để đảm bảo rằng tác phẩm nghệ thuật của họ trông chính xác đúng theo chủ định. Màn hình ProArt PA247CV được hiệu chuẩn trước khi xuất xưởng và đạt chứng nhận Calman Verified để bảo đảm độ chính xác màu vượt trội (∆E < 2). ', '7450000', 'asus_pro24.jpg', 3, 6, 10),
(9, 'Màn hình ASUS ROG Strix XG309CM 30\" IPS 240Hz 1ms G-Sync HDR10', 'Màn hình', 6, 'Mới', 'Đánh giá chi tiết màn hình ASUS ROG Strix XG309CM 30 inch IPS 220Hz 1ms G-Sync HDR10\r\nMàn hình chuyên game ASUS ROG Strix XG309CM được thiết kế đặc biệt dựa trên nhu cầu của game thủ chuyên nghiệp, lấy game thủ làm trọng tâm để tạo nên một màn hình máy tính chất lượng. Hãy cùng xem qua siêu phẩm này để xem nó có gì khiến người dùng đứng ngồi không yên nhé.\r\nTrải nghiệm màn hình siêu rộng\r\nMàn hình ASUS ROG Strix XG309CM sở hữu màn hình kích thước lớn, lên đến 30 inch. Độ phân giải Full HD tiêu chuẩn dưới tấm nền Fast IPS giúp tái tạo hình ảnh chân thật và sống động, bạn sẽ được trải nghiệm hình ảnh rõ nét đến từng chi tiết.\r\nTỷ lệ khung hình 21:9 mới giúp mở rộng khả năng hiển thị hơn so với tỷ lệ 16:9 truyền thống. Nó cung cấp một không gian hiển thị rộng, bạn có thể mở nhiều cửa sổ trong lúc làm việc.\r\n\r\nTần số quét cao - thời gian phản hồi nhanh\r\nASUS ROG Strix XG309CM được trang bị tấm nền tiên tiến, cho phép bạn bật / tắt màn hình nhanh gấp bốn lần so với nhiều màn hình chuyên game thông thường. Hình ảnh trên màn hình sẽ vô cùng mượt mà và liền mạch dù bạn có đang chạy tác vụ nặng cỡ nào.', '12550000', 'asus_rog.jpg', 2, 6, 13),
(13, 'Bàn phím AKKO ACR Pro 68', 'Bàn phím', 8, 'Mới', 'Đánh giá chi tiết bàn phím AKKO ACR Pro 68\r\nNổi tiếng với những thiết kế đơn giản nhưng vẫn mang vẻ đẹp riêng dành cho những gaming gear của mình, Akko luôn tới những sản phẩm chất lượng. Hôm nay sẽ là chiếc bàn phím nhỏ nhắn, xinh xắn, AKKO ACR  Pro 68. Cùng GEARVN xem chiếc bàn phím từ AKKO sẽ mang lại cho chúng ta những gì nhé !\r\n\r\nThiết kế 68 phím nhỏ gọn\r\nHoàn thiện với thiết kế 68 phím, bàn phím AKKO ACR Pro 68 mang đến vóc dáng nhỏ gọn nhưng vẫn mang đến sự cứng cáp cần thiết dành cho bàn phím cơ, thích hợp dành cho mọi không gian bàn làm việc và thuận tiện trong setup, quá trình sử dụng. Lớp vỏ ngoài của AKKO ACR Pro 68 được làm trắng đục nhằm tăng thêm sự huyền ảo mà dãy đèn LED RGB bên trong mang tới. Điểm nhấn không thể bỏ qua nữa đó chính là một tấm hình nhỏ với hình tượng gấu trúc đặt làm trọng tâm và làm ánh vàng lên, tạo nên sự thu hút mọi ánh nhìn khi lướt qua chiếc bàn phím.\r\n\r\nKết cấu cao cấp\r\nBàn phím AKKO ACR Pro 68 được sở hữu một kết cấu cao cấp mà ít khi được thấy những sản phẩm AKKO tiền nhiệm trước đây, đó là miếng đệm Gasket Mount. Miếng đệm lót là trung gian giữa phần phím và case, từ đó tạo ra độ flex rõ ràng hơn. Kết hợp cùng tấm foam tiêu âm làm bằng poron, AKKO ACR Pro 68 tạo ra tiếng động ít nhất có thể, tất cả hướng tới trải nghiệm gõ phím tốt nhất cho người dùng.', '2850000', 'akko_68.jpg', 4, 5, 3),
(15, 'Bàn phím cơ AKKO 3098N Multi-modes Black Gold (TTC switch)', 'Bàn phím', 9, 'Mới', 'Đánh giá sản phẩm bàn phím cơ AKKO 3098N Multi-modes Black Gold (TTC switch)\r\nAKKO 3098N Multi-modes Black Gold (TTC switch) thuộc dòng bàn phím 2 đến 3 triệu thích hợp để chơi game hay làm việc hằng ngày. Nếu bạn đang cân nhắc để lựa chọn cho mình chiếc bàn phím phù hợp thì hãy cùng GEARVN tìm hiểu về sản phẩm này nhé!\r\n\r\nKeycap làm từ nhựa PBT Double-Shot chắc chắn, bền bỉ\r\nKeycap của bàn phím Akko được đúc từ nhựa PBT cùng công nghệ in Double-Shot bền bỉ. Tạo nên độ bền theo thời gian cho những lần gõ phím trên từng Keycap. Dù bạn có nhấn bao nhiêu lần trên từng con phím mặt chữ vẫn sẽ bám cực tốt, không bị phai đi. Một trong những dòng bàn phím cơ có trên thị trường hỗ trợ tính năng chống bám vân tay, mồ hôi cực tốt. Bạn yên tâm chiếc bàn phím luôn được giữ trong trạng thái tươi mới\r\nProfile ASA chính hãng từ Akko\r\nASA Profile là một profile được Akko nghiên cứu và phát triển. ASA sở hữu bộ keycap bầu tròn như đàn anh SA của mình. Tuy nhiên ASA được đánh giá có độ cao vừa phải giúp bạn dễ dàng làm quen hơn, khi gõ cũng cho ra âm thanh cuốn hút hơn.', '2950000', 'akko_3098.jpg', 5, 5, 3),
(16, 'Bàn phím cơ AKKO 3108 Plus Black & Cyan', 'Bàn phím', 7, 'Mới', 'Đánh giá chi tiết bàn phím cơ AKKO 3108 Plus Black & Cyan\r\nBàn phím AKKO đã quá nổi tiếng với cộng đồng người dùng. Thiết kế thu hút, mẫu mã đa dạng và hãng không ngừng nâng cấp sản phẩm để mang đến trải nghiệm tốt nhất cho người dùng. Và AKKO 3108 Plus Black & Cyan một lần nữa chiếm trọn spotlight phân khúc bàn phím cơ giá rẻ, chất lượng.\r\n\r\nThiết kế AKKO 3108 Plus Black & Cyan hiện đại\r\nBàn phím cơ AKKO 3108 Plus Black & Cyan sở hữu tông màu đen cá tính. Sự kết hợp hài hòa giữa tông đen và xanh khiến bàn phím mang nét đơn giản xen chút cuốn hút nhưng lại không bị nhàm chán. \r\n\r\nCase bàn phím được hoàn thiện bằng chất liệu nhựa cao cấp giúp tổng thể bàn phím chắc chắn và cứng cáp. Kiểu dáng bàn phím Full size sẽ giúp bạn thực hiện đầy đủ mọi nhu cầu từ đánh máy, nhập liệu đến viết code. \r\n\r\nKeycap và switch chất lượng cao\r\nAKKO 3108 Plus Black & Cyan được trang bị bộ keycap PBT Double-shot, Cherry profile mang đến trải nghiệm gõ phím mượt và êm ái. Công nghệ in Double-shot giúp các kí tự trên bàn phím được rõ nét và đảm bảo được độ bền trong quá trình sử dụng.\r\n', '1850000', 'akko3108.jpg', 3, 5, 4),
(17, 'PC GVN PHANTOM i2060', 'PC', 4, 'Mới', 'Chi tiết về GVN PHANTOM i2060\r\nMainboard MSI MAG B660M MORTAR DDR4\r\nMainboard MSI MAG B660M MORTAR WIFI DDR4 là bo mạch chủ sử dụng chipset B660 của Intel, hỗ trợ vi xử lý mới nhất hiện nay - Intel Core thế hệ 12 với socket LGA 1700. Sở hữu một ngoại hình bắt mắt với những chi tiết được hoàn thiện với chất lượng cao.\r\n\r\n\r\n\r\nMainboard MSI MAG B660M MORTAR DDR4 ra đời sau khi trải qua thông qua các cuộc thử nghiệm chất lượng một cách kỹ lưỡng và được thiết kế để trở thành biểu tượng của sự chắc chắn và bền bỉ. Với kinh nghiệm đã thu thập được, MSI MAG B660M MORTAR DDR4 được trang bị những công nghệ tiên tiến nhất cung cấp hiệu suất mạnh mẽ nhất.\r\n\r\nCPU Intel Core i7 12700F\r\nCPU Intel Core i7-12700F thuộc Intel Gen 12 mạnh mẽ nhất hiện nay từ đội xanh, mang đến sức mạnh ấn tượng cho người dùng. Với 12 nhân 20 luồng đi kèm với tần số cơ bản là 2.10 GHz và turbo boost lên đến 4.9 GHz, i7-12700F đem lại tốc độ xử lý tác vụ vô cùng nhanh và khả năng hoạt động đa nhiệm mượt mà khi học tập, làm việc và giải trí.\r\n\r\n\r\nRAM PNY XLR8 Silver 1x8GB 3600 RGB\r\nRAM PNY XLR8 Silver 1x8GB 3600 RGB góp phần vào buổi trình diễn ánh sáng khi được trang bị dải LED RGB 16 triệu màu, hỗ trợ tùy chỉnh dễ dàng bằng phần mềm. Khoác bên ngoài là lớp giáp tản nhiệt bạc trắng tinh khôi tạo nên điểm nhấn trong chiếc case, đây sẽ là một trong những lựa chọn RAM LED RGB xứng đáng với túi tiền cho anh em.\r\n\r\n\r\nPNY XLR8 Silver 1x8GB 3600 RGB sở hữu thêm công nghệ XMP giúp tăng cường hiệu suất, duy trì khả năng hoạt động tối và cung cấp khả năng ép xung mạnh mẽ cho những “dân chơi” yêu thích sự tìm tòi, khám phá.\r\n\r\nVGA GIGABYTE GeForce RTX 2060 D6 6G\r\nGIGABYTE GeForce RTX 2060 D6 6G vẫn giữ được vẻ ngoài gaming trước đó. Khoác lên màu đen mạnh mẽ cùng các góc cạnh được hoàn thiện một cách bắt mắt, GIGABYTE GeForce RTX 2060 D6 6G sẽ làm nổi bật chiếc case nói riêng và góc gaming nói chung.\r\n', '25500000', 'pc_i2060.jpg', 1, 7, 7),
(18, 'PC GVN VIPER i1050Ti', 'PC', 2, 'Mới', 'Chi tiết về GVN VIPER i1050Ti\r\nMainboard GIGABYTE B560M AORUS PRO (rev. 1.0)\r\nMở màn cho sức mạnh của GVN VIPER i1050Ti sẽ là chiếc mainboard GIGABYTE B560M AORUS PRO (rev. 1.0) Đáp ứng đúng tiêu chí giá rẻ nhưng GIGABYTE B560M AORUS PRO (rev. 1.0) vẫn mang hiệu năng và khả năng tận dụng sức mạnh tuyệt vời. Với socket LGA 1200, MSI MAG B560M MORTAR WIFI có thể tận sức mạnh của những CPU Intel Gen 11 và Gen 10. Trang bị những công nghệ tiên tiến nhất như Core Boost, tấm M.2 Shield Frozr cùng công nghệ ép xung OC RAM, GIGABYTE B560M AORUS PRO (rev. 1.0) xứng đáng có tên trong những bộ PC Gaming giá rẻ hiện nay.\r\n\r\n\r\n\r\nCPU Intel Core i5 11400F\r\nTiếp nối sự thành công của người anh tiền nhiệm 10400F, i5-11400F vẫn là một đối trọng mạnh mẽ trong phân khúc tầm trung của CPU. Khả năng gaming, stream game được thực hiện một cách mượt mà với 6 nhân 12 luồng trên i5-11400F. Tốc độ xử lý đạt tối đa lên đến 4.4GHz giúp cho i5-11400F hoàn thành mọi tác vụ với tiến độ nhanh hơn.\r\n\r\n\r\nRAM PNY XLR8 Silver 1x8GB 3600 RGB\r\nSở hữu dải đèn LED RGB có thể phát sáng với góc lên đến 120 độ cùng tốc độ truyền tải nhanh, đó là tất cả những gì mà RAM PNY XLR8 Silver RGB đem đến cho người dùng. Không những đem đến hiệu năng đa nhiệm mạnh mẽ mà PNY XLR8 Silver RGB còn giúp tô điểm thêm dàn PC Gaming của chúng ta, tạo nên những bữa tiệc ánh sáng hoành tráng.\r\n\r\n\r\nVGA MANLI GeForce GTX 1050 Ti 4GB GDDR5\r\nCung cấp khả năng chơi game trên GVN VIPER i1050Ti sẽ là MANLI GeForce GTX 1050 Ti. Đến tay người dùng với đúng tiêu chí giá rẻ, MANLI GeForce GTX 1050 Ti vẫn có một hiệu năng ổn định, cho phép game thủ có thể trải nghiệm những tựa game Esport với mức setting phù hợp.', '15500000', 'pc_1050.jpg', 2, 7, 7),
(19, 'PC GVN MINION i1650 - White Edition', 'PC', 5, 'Mới', 'Chi tiết về GVN Minion i1650\r\nMainboard MSI H510M Pro-E\r\nMainboard MSI H510M Pro-E sẽ là cầu nối tất cả linh kiện trong chiếc GVN MINION i1650. Là chiếc bo mạch chủ giá rẻ sở hữu socket LGA 1200 cho khả năng tương thích tốt với nhiều bộ vi xử lý hiện nay như Intel Gen 10, Gen 11 và tận dụng tối đa sức mạnh cho hiệu năng xử lý tốt nhất.\r\n\r\n\r\n\r\nCPU Intel Core i3 10105F\r\nĐóng vai trò là bộ não cho GVN MINION i1650, CPU Intel Core i3 10105F là lựa chọn xứng đáng nhất của PC Gaming. Với mức giá phải chăng, i3-10105F vẫn mang lại khả năng xử lý nhanh với mức xung nhịp tối đa lên 4.4GHz cùng công nghệ siêu phân luồng (Hyper-Threading). Và tự tin rằng, i3-10105F sẽ cân tốt những tựa game Esport hiện nay như Liên Minh Huyền Thoại, FO4, Valorant, …\r\n\r\nGVN Viper i1660Ti được GEARVN trang bị SSD hỗ trợ người dùng tự động ép xung lên đến tần số cao nhất mà Mainboard hỗ trợ. Chỉ cần cắm và chạy, không cần tinh chỉnh trong Bios. Trang bị công nghệ HyperX Infrared Sync  giúp hệ thống của bạn đồng bộ hiệu ứng cực kỳ dễ dàng mà không cần phải cắm dây tín hiệu RGB.\r\n\r\nHệ thống ánh sáng RGB tuyệt đẹp với phong cách mạnh mẽ.\r\nCông nghệ đồng bộ hồng ngoại HyperX Infrared Sync Technology.\r\nIntel XMP-ready được tối ưu hóa cho các chipset mới nhất của Intel.\r\nTính năng Plug N Play ở 2400 MHz và 2666 MHz.\r\nVGA MSI GeForce GTX 1650 D6 VENTUS XS OC 4GB\r\nSức mạnh xử lý đồ họa trên GVN MINION i1650 được khẳng định với chiếc card màn hình MSI GeForce GTX 1650 D6 VENTUS XS OC 4GB. Đem đến một thiết kế mới lạ, MSI GeForce GTX 1650 D6 VENTUS XS OC 4GB còn sở hữu khả năng đồ họa tuyệt vời với 4GB GDDR6 cùng kiến trúc NVIDIA Turing, cung cấp khả năng chơi những tựa game Esport như LOL, FO4, Valorant,...với mức setting cao và những game AAA ở mức đồ họa phù hợp.\r\n\r\n\r\n\r\nTrang bị 2 cánh quạt tản nhiệt, tối ưu hiệu suất hoạt động cho MSI GeForce GTX 1650 D6 VENTUS XS OC 4GB.\r\n\r\nSSD PNY CS900 240G 2.5\" Sata 3\r\nGVN MINION i1650 sở hữu không gian lưu trữ 240GB đến từ SSD PNY CS900 240G 2.5\" Sata 3. Tốc độ đọc/ghi file ấn tượng lần lượt là 535MB/s và 500MB/s sẽ là những thông số cần thiết cho việc sao lưu, lưu trữ dữ liệu như video, hình ảnh và game. Với bộ nhớ SSD, tối ưu tốc độ khởi động cho dàn PC chơi game của chúng ta.', '8950000', 'pc_1650.jpg', 1, 7, 7),
(20, 'Tai nghe Steelseries Arctis 7 Plus Wireless White', 'Tai Nghe', 13, 'Mới', 'Best wireless gaming headset — PC Gamer\r\n\r\nĐược thiết kế cho PC với cổng USB-C nhưng tương thích nhiều hệ thống PS5, PS4, PC, Android, Switch, USB-C iPad và nhiều nữa.\r\nDongle USB-C nhỏ gọn mới hỗ trợ đa nền tảng với kết nối không dây 2.4GHz độ trễ thấp.\r\nTrang bị tính năng sạc qua cổng USB-C, chỉ cần sạc 15 phút có 3 giờ sử dụng.\r\nPin nâng cấp lên 30 giờ.\r\nMicrophone tốt nhất cho game: Mic chống ồn ClearCast được chứng nhận bởi Discord.', '4850000', 'steel7p.jpg', 3, 4, 6),
(21, 'Tai nghe SteelSeries Arctis 1', 'Tai nghe', 9, 'Mới', 'Đánh giá chi tiết Tai nghe nghe gaming SteelSeries Arctis 1\r\n\r\nSteelSeries Arctis 1 là chiếc tai nghe máy tính gaming giá rẻ đa năng và hoạt động với mọi nền tảng. Từ PC đến PS4 và Xbox. Dễ dàng mang đi xa với điện thoại hoặc Switch. \r\n\r\nVới drivers loa chất lượng cao tương tự như chiếc tai nghe Arctis 7 đã từng giành giải thưởng, Arctis 1 có âm thanh Arctis đặc trưng, ​​nhấn mạnh chất thanh tinh tế nhưng quan trọng để mang đến cho bạn lợi thế về âm thanh.\r\n\r\nArctis 1 là chiếc tai nghe đa năng và hoạt động với mọi nền tảng. Từ PC đến PS4 và Xbox. Dễ dàng mang đi xa với điện thoại hoặc Switch.\r\n\r\nMicro ClearCast đã được Discord chứng nhận sử dụng thiết kế hai chiều, thiết kế này đã từng được sử dụng bởi các phi hành đoàn trên tàu sân bay. Nó cung cấp khả năng khử tiếng ồn vượt trội để giọng nói của bạn nghe rõ và tự nhiên. Và tất nhiên nó cũng có thể tháo rời dễ dàng khi di chuyển.', '1350000', 'steel1.jpg', 5, 4, 5),
(22, 'Tai nghe Steelseries Arctis Nova Pro', 'Tai nghe', 7, 'Mới', 'Đánh giá chi tiết Steelseries Arctis Nova Pro\r\nThiết kế đặc biệt dành cho game thủ\r\nTai nghe SteelSeries Arctis Nova Pro sở hữu một thiết kế độc phá và mới mẻ hơn so với những dòng tai nghe trước, không còn mang cảm giác mỏng manh, thay vào đó là sự cứng cáp và chắc chắn hơn. Nhưng trọng lượng của chiếc tai nghe không dây này vẫn khá nhẹ, nên không mang lại cảm giác nặng nề khi đeo quá lâu.\r\nPhần headband cũng được cải tiến hơn những dòng sản phẩm trước đây, đã thay thế cáp co giãn bằng vải thường dùng cho kính mắt, có tính năng co giãn cao và hạn chế đứt cáp hiệu quả. Phần chụp tai bằng da sang trọng, mang lại cảm giác mềm mại khi đeo trên tai\r\n\r\nChất lượng âm thanh \r\nDù định hướng sản xuất của sản phẩm này là tai nghe gaming nhưng Steelseries Arctis Nova Pro vẫn được trang bị hệ thống âm thanh chất lượng với âm bass chân thực, sống động. Bên cạnh đó, Steelseries Arctis Nova Pro còn có khả năng tái tạo chất lượng âm thanh một cách chuyên nghiệp nhờ sự kết hợp hoàn hảo giữa Nova Pro Acoustic System và Premium High Fidelity Drivers, hứa hẹn mang trải nghiệm \"từ trước đến nay chưa từng có\".\r\nTương thích nhiều thiết bị\r\nĐiểm cộng thêm cho Steelseries Arctis Nova Pro phải nói đến chính là microphone lọc tiếng ồn hai chiều vượt trội, giúp loại bỏ tạp âm và giọng nói bạn sẽ được phát ra rõ ràng hơn.', '6950000', 'steel_pro.jpg', 3, 4, 6),
(23, 'Ghế Corsair TC200 Leatherette Light Grey/White', 'Ghế', 7, 'Mới', 'Đánh giá chi tiết ghế Corsair TC200 Leatherette Light Grey/White\r\nKhông chỉ sở hữu thiết kế hầm hố qua những đường nét góc cạnh được làm một cách tỉ mỉ, Corsair TC200 với tông màu sang trọng Light Grey/White cùng chất liệu da Leatherette sẽ làm nổi bật cho mọi góc máy.\r\n\r\nThiết kế hầm hố nhưng không kém phần sang trọng\r\nDòng sản phẩm ghế gaming được lấy cảm hứng từ những dòng ghế xe đua với form dáng cao to, chắc chắn Corsair TC200 Leatherette Light Grey/White tạo cảm giác ngồi thoải mái trong nhiều giờ liền qua thiết kế ghế công thái học và mang đến sự phấn khởi cho tinh thần với các tựa game yêu thích. Kết với hài hòa giữa 2 tông màu xám trắng tạo nên vẻ ngoài vô cùng sang trọng, đẳng cấp bạn hoàn toàn có thể đặt Corsair TC200 vào bất kỳ không gian nào. \r\n\r\nThêm vào đó, ở phiên bản da Leatherette vô cùng bền bỉ người chơi hoàn toàn có thể tự vệ sinh ghế một cách dễ dàng.\r\n\r\nCorsair TC200 Leatherette Light Grey/White cùng nhiều tính năng nổi bật\r\nThiết bị Gaming Gear từ Corsair luôn được đánh giá cao về sự hoàn thiện và thiết kế. Bạn có thể dễ dàng nhận thấy qua các thiết bị chuột máy tính, bàn phím chơi game, tai nghe máy tính và cả những dòng ghế gaming ở nhiều phân khúc khác nhau. \r\n\r\nGEARVN-ghe-corsair-tc200-leatherette-light-grey-white\r\n\r\nTrên Corsair TC200 Series cũng không ngoại lệ, khi được trang bị một số tính năng nổi bật hiện đại hỗ trợ tối đa cho người dùng như:\r\n\r\nCơ chế ngả lưng 90-180 độ bạn hoàn toàn có thể ngả ghế và nghỉ ngơi sau thời gian dài chơi game và học tập, làm việc.\r\n\r\nKê tay 4D dễ dàng hiệu chỉnh lên/xuống, trái/phải,...hỗ trợ phần cánh tay, khuỷu tay tránh được tình trạng đau mỏi.\r\n\r\nNâng lên/hạ xuống dễ dàng giúp bạn có những tư thế ngồi thoải mái với độ cao phù hợp.\r\n\r\nĐi kèm phần tựa đầu bằng chất liệu cao cấp, dễ dàng điều chỉnh mang đến tư thế ngồi hạn chế được những cơ đau vai, gáy. \r\n\r\nSự lựa chọn tốt nhất cho form người cao lớn\r\nNhìn tổng thể Corsair TC200 Leatherette Light Grey/White sở hữu thiết kế khá sang trọng, nhẹ nhàng nhưng vẫn mang đậm dấu ấn gaming qua các chi tiết góc cạnh.\r\n\r\nPhiên bản nâng cấp của T3 Rush, TC200 sở hữu kích thước to lớn phù hợp với nhiều form người nhờ thiết kế to lớn 56cm x 58cm với bề mặt ghế rộng, lưng ghế form ôm sát lưng cao 83cm tạo cảm giác thoải mái cho người chơi trong cả ngày dài. Rất thích hợp cho người dùng với chiều cao lên đến 1m96. \r\n\r\nCảm giác ngồi chắc chắn nhờ Piston, khung thép cao cấp\r\n\r\nĐể hoàn thiện sản phẩm dành cho form người to cao, Corsair TC200 được cấu tạo bằng khung thép cao cấp mang đến sự chắc chắn cho người dùng. Cùng với phần trục lên/xuống Piston Class 4, chân kim loại siêu bền có thể chịu tải trọng lên đến 121KG.', '8450000', 'cor_tc200.jpg', 3, 3, 15),
(24, 'Ghế Corsair T3 RUSH Grey/Charcoal', 'Ghế', 5, 'Mới', 'Đánh giá chi tiết ghế gaming Corsair T3 RUSH Grey/Charcoal\r\nCorsair là cái tên lão làng trong ngành thiết bị tai nghe gaming, chuột và nổi bật trong số đó là dòng sản phẩm ghế gaming. T3 Rush Grey/Charcoal là model ghế gaming mới nhất của hãng cho năm nay. Với nhiều nâng cấp và đổi mới về cả chất liệu lẫn thiết kế, T3 RUSH Grey/Charcoal thật sự đã mang đến một làn gió mới cho fan hâm mộ lâu năm của Corsair. \r\n\r\nGối Memory Foam thông minh\r\n\r\nPhần gối lưng làm bằng vật liệu cao su non bọc nhung, Rất mềm rất êm và thiết kế của nó vừa vặn để cố định vào lưng ghế mà không cần tới dây đai như các loại ghế gaming khác. Về phần gối đầu, tuy không làm bằng cao su non nhưng cũng khá êm và kích thước vừa đủ.\r\n\r\nThiết kế lưng Egonomic ( Công thái học )\r\nĐây cũng là một thiết kế \"thông minh\" của Corsair T3 Rush, được thừa hưởng từ phiên bản T1. Về kích thước ghế, chúng tôi nhận thấy Corsair T3 Rush có kích thước trung bình, phù hợp với người dưới 80Kg và có phần lưng ghế uống cong rất đẹp về thẩm mỹ và hiệu quả cao về độ \"FIT\". Trong quá trình trải nghiệm, chúng tôi thấy rằng phần lưng ghế của Corsair T3 Rush thực sự rất \"ôm\" và cho cảm giác rất dễ chịu thoải mái.\r\n\r\nKhung 100% kim loại \r\nCorair T3 Rush sử dụng 100% kim loại cho bộ khung ghế, với đẳng cấp chất lượng và thương hiệu đã được khẳng định, chúng ta hoàn toàn yên tâm về độ bền cùng sự ổn định lâu dài của sản phẩm.\r\n\r\nKê tay 4D cao cấp\r\nOption tay xoay 4 chiều giúp cho việc tùy chọn vị trí kê tay rất linh hoạt.\r\n\r\nChân bằng nhựa nilon bền bỉ\r\nChân của Corsair T3 Rush làm bằng nhựa nilon (thay vì kim loại). Tất nhiên nhựa này rất bền và đảm bảo an toàn 100% cho người sử dụng. Bánh xe của ghế chất lượng tương tốt\r\n', '6550000', 'cor_t3.jpg', 1, 3, 15),
(25, 'Ghế Corsair TC60 Fabric - Black', 'Ghế', 8, 'Mới', 'Đánh giá chi tiết Ghế Corsair TC60 Fabric\r\nThoãi mái thư giãn cả ngày dài\r\nSự vừa vặn thoải mái của TC60 FABRIC được tạo nên từ lớp đệm rộng, lớp vải mềm thoáng khí, chỉ giữ nhiệt tối thiểu để bạn luôn thoải mái suốt cả ngày dài, trong mọi môi trường.\r\n\r\nThiết kế linh hoạt\r\nTay vịn có thể điều chỉnh cao di chuyển theo cả ba chiều, 100mm điều chỉnh chiều cao ghế và lưng ghế ngả 105° với độ nghiêng ghế đồng bộ 10° có nghĩa là bạn có thể thoải mái ở mọi góc độ.\r\n\r\nBánh xe kép 60MM\r\nThiết kế bánh xe kép đường kính 60mm giúp lướt dễ dàng trên hầu hết các bề mặt.', '4050000', 'cor_tc60.jpg', 4, 3, 15);

--
-- Chỉ mục cho các bảng đã đổ
--

--
-- Chỉ mục cho bảng `product`
--
ALTER TABLE `product`
  ADD PRIMARY KEY (`id_sp`),
  ADD KEY `thuonghieu` (`thuonghieu`),
  ADD KEY `subcate` (`subcate`);

--
-- AUTO_INCREMENT cho các bảng đã đổ
--

--
-- AUTO_INCREMENT cho bảng `product`
--
ALTER TABLE `product`
  MODIFY `id_sp` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=26;

--
-- Các ràng buộc cho các bảng đã đổ
--

--
-- Các ràng buộc cho bảng `product`
--
ALTER TABLE `product`
  ADD CONSTRAINT `subcate` FOREIGN KEY (`subcate`) REFERENCES `subcategory` (`id_subcate`),
  ADD CONSTRAINT `thuonghieu` FOREIGN KEY (`thuonghieu`) REFERENCES `thuonghieu` (`id_th`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
